spring:
  cloud:
    config:
      label: master
      uri: http://localhost:8888
      username: gigi
      password: test1234
  datasource:
    url: jdbc:mysql://127.0.0.1:6666/testdb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: test1234
  security:
    user:
      name: admin
      password: $2a$10$QpA9JjOQiciPKokmwlxEYOPtZLIHfTFECvDeL8in.ZGWVUY24Cx/a  